import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Aplicação Hello World',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <ul>
            <li>
              <Link href="/about">Sobre</Link>
              <Link href="/nao-existe">404</Link>
              <Link href="/blog/post">Detalhes</Link>
            </li>
          </ul>
        </header>
        {children}

        <footer>footer</footer>
      </body>
    </html>
  )
}
